schemaVersion: 2.2.2
metadata:
  attributes:
    metadata-name-field: generateName
    metadata-name-original-value: jamaica
  name: jamaica
  namespace: sashirestela-dev
attributes:
  che-theia.eclipse.org/sidecar-policy: mergeImage
projects:
  - name: jamaica
    git:
      remotes:
        origin: https://github.com/sashirestela/jamaica.git
components:
  - name: universal-developer-image
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      volumeMounts:
        - name: m2
          path: /home/user/.m2
      mountSources: true
      env:
        - name: GEMINI_API_KEY
          value: AIzaSyB8Wq9eV3ikjiMQll-FFqe8wK5XOmnWF80
  - name: m2
    volume:
      size: 5Gi
commands: []